In [4]:
import pandas as pd

# Прочитайте файл 2017_jun_final.csv за допомогою методу read_csv
df = pd.read_csv('2017_jun_final.csv')
print(df)

         N                 Должность Язык.программирования Специализация  \
0        1        Junior QA engineer                   NaN     Manual QA
1        2        Junior QA engineer                   NaN     Manual QA
2        3         Software Engineer               C#/.NET           NaN
3        4         Software Engineer            JavaScript           NaN
4        5  Senior Software Engineer            JavaScript           NaN
...    ...                       ...                   ...           ...
8699  8700               QA engineer                   NaN     Manual QA
8700  8701                 Marketing                   NaN           NaN
8701  8702  Junior Software Engineer            Ruby/Rails           NaN
8702  8703                 Team lead                   NaN           NaN
8703  8704  Senior Software Engineer                  Java           NaN

     Общий.опыт.работы Опыт.работы.на.текущем.месте  Зарплата.в.месяц  \
0                  0.5                          0.5               400
1     меньше 3 месяцев             меньше 3 месяцев               430
2                    4                            1              2500
3                    5                            4              2000
4       10 и более лет                          0.5              4500
...                ...                          ...               ...
8699                 1             меньше 3 месяцев               700
8700               0.5                          0.5               400
8701                 1                          0.5               800
8702                 6                            4              2600
8703                 7                            2              5000

      Изменение.зарплаты.за.12.месяцев    Город     Размер.компании  ...  \
0                                    0  Харьков       до 10 человек  ...
1                                  130  Харьков  свыше 1000 человек  ...
2                                  800     Киев     до 1000 человек  ...
3                                  400   Одесса      до 200 человек  ...
4                                  500   Другой       до 10 человек  ...
...                                ...      ...                 ...  ...
8699                               700   Одесса       до 50 человек  ...
8700                               120     Киев       до 50 человек  ...
8701                               500    Львов       до 10 человек  ...
8702                                 0    Днепр  свыше 1000 человек  ...
8703                               800   Одесса     до 1000 человек  ...

     Еще.студент Уровень.английского                    Предметная.область  \
0           True       ниже среднего                         iOS,eCommerce
1           True       выше среднего                        Веб-разработка
2          False             средний  Веб-разработка,Корпоративные системы
3          False       ниже среднего   Desktop Applications,Веб-разработка
4          False             средний   Desktop Applications,Веб-разработка
...          ...                 ...                                   ...
8699       False             средний          Android,Desktop Applications
8700       False       ниже среднего                             eCommerce
8701       False       выше среднего  Веб-разработка,Корпоративные системы
8702       False         продвинутый                       Финансы и банки
8703       False       выше среднего                        Веб-разработка

          Дата.заполнения                                         User.Agent  \
0     12/06/2017 12:38:08  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
1     12/06/2017 12:42:51  Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...
2     12/06/2017 13:02:47  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
3     12/06/2017 13:03:01  Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...
4     12/06/2017 13:03:47  Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...
...                   ...                                                ...
8699  12/07/2017 15:45:24  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....
8700  12/07/2017 17:00:06  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
8701  12/07/2017 17:32:26  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...
8702  12/07/2017 18:14:59  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...
8703  12/07/2017 21:28:57  Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X...

       exp current_job_exp salary Валюта  cls
0      0.5             0.5    400    NaN   QA
1      0.0             0.0    430    NaN   QA
2      4.0             1.0   2500    NaN  DEV
3      5.0             4.0   2000    NaN  DEV
4     10.0             0.5   4500    NaN  DEV
...    ...             ...    ...    ...  ...
8699   1.0             0.0    700    NaN   QA
8700   0.5             0.5    400    NaN  NaN
8701   1.0             0.5    800    NaN  DEV
8702   6.0             4.0   2600    NaN   PM
8703   7.0             2.0   5000    NaN  DEV

[8704 rows x 25 columns]

In [5]:
# Прочитайте отриману таблицю, використовуючи метод head
print(df.head())

   N                 Должность Язык.программирования Специализация  \
0  1        Junior QA engineer                   NaN     Manual QA
1  2        Junior QA engineer                   NaN     Manual QA
2  3         Software Engineer               C#/.NET           NaN
3  4         Software Engineer            JavaScript           NaN
4  5  Senior Software Engineer            JavaScript           NaN

  Общий.опыт.работы Опыт.работы.на.текущем.месте  Зарплата.в.месяц  \
0               0.5                          0.5               400
1  меньше 3 месяцев             меньше 3 месяцев               430
2                 4                            1              2500
3                 5                            4              2000
4    10 и более лет                          0.5              4500

   Изменение.зарплаты.за.12.месяцев    Город     Размер.компании  ...  \
0                                 0  Харьков       до 10 человек  ...
1                               130  Харьков  свыше 1000 человек  ...
2                               800     Киев     до 1000 человек  ...
3                               400   Одесса      до 200 человек  ...
4                               500   Другой       до 10 человек  ...

  Еще.студент Уровень.английского                    Предметная.область  \
0        True       ниже среднего                         iOS,eCommerce
1        True       выше среднего                        Веб-разработка
2       False             средний  Веб-разработка,Корпоративные системы
3       False       ниже среднего   Desktop Applications,Веб-разработка
4       False             средний   Desktop Applications,Веб-разработка

       Дата.заполнения                                         User.Agent  \
0  12/06/2017 12:38:08  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
1  12/06/2017 12:42:51  Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...
2  12/06/2017 13:02:47  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
3  12/06/2017 13:03:01  Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...
4  12/06/2017 13:03:47  Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...

    exp current_job_exp salary Валюта  cls
0   0.5             0.5    400    NaN   QA
1   0.0             0.0    430    NaN   QA
2   4.0             1.0   2500    NaN  DEV
3   5.0             4.0   2000    NaN  DEV
4  10.0             0.5   4500    NaN  DEV

[5 rows x 25 columns]

In [6]:
# Визначте розмір таблиці за допомогою методу shape
print(df.shape)

(8704, 25)

In [9]:
# Визначте типи всіх стовпців за допомогою dataframe.dtypes
print(df.dtypes)

N                                     int64
Должность                            object
Язык.программирования                object
Специализация                        object
Общий.опыт.работы                    object
Опыт.работы.на.текущем.месте         object
Зарплата.в.месяц                      int64
Изменение.зарплаты.за.12.месяцев      int64
Город                                object
Размер.компании                      object
Тип.компании                         object
Пол                                  object
Возраст                               int64
Образование                          object
Университет                          object
Еще.студент                            bool
Уровень.английского                  object
Предметная.область                   object
Дата.заполнения                      object
User.Agent                           object
exp                                 float64
current_job_exp                     float64
salary                                int64
Валюта                               object
cls                                  object
dtype: object

In [10]:
# Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи isnull та sum)
miss_perc = df.isnull().sum() / len(df) * 100
print(miss_perc)

N                                    0.000000
Должность                            0.000000
Язык.программирования               44.232537
Специализация                       82.938879
Общий.опыт.работы                    0.000000
Опыт.работы.на.текущем.месте         0.000000
Зарплата.в.месяц                     0.000000
Изменение.зарплаты.за.12.месяцев     0.000000
Город                                0.000000
Размер.компании                      0.000000
Тип.компании                         0.000000
Пол                                  0.000000
Возраст                              0.000000
Образование                          0.000000
Университет                          4.113051
Еще.студент                          0.000000
Уровень.английского                  0.000000
Предметная.область                   2.562040
Дата.заполнения                      0.000000
User.Agent                           0.000000
exp                                  0.000000
current_job_exp                      0.000000
salary                               0.000000
Валюта                              99.885110
cls                                 18.083640
dtype: float64

In [24]:
# Видаліть усі стовпці з пропусками, крім стовпця Мова програмування
target_column = 'Язык.программирования'
df_cleaned = df[[target_column]]
for column in df.columns:
    if column != target_column and df[column].notnull().all():
        df_cleaned[column] = df[column]

print(df_cleaned)

     Язык.программирования     N                 Должность Общий.опыт.работы  \
0                      NaN     1        Junior QA engineer               0.5
1                      NaN     2        Junior QA engineer  меньше 3 месяцев
2                  C#/.NET     3         Software Engineer                 4
3               JavaScript     4         Software Engineer                 5
4               JavaScript     5  Senior Software Engineer    10 и более лет
...                    ...   ...                       ...               ...
8699                   NaN  8700               QA engineer                 1
8700                   NaN  8701                 Marketing               0.5
8701            Ruby/Rails  8702  Junior Software Engineer                 1
8702                   NaN  8703                 Team lead                 6
8703                  Java  8704  Senior Software Engineer                 7

     Опыт.работы.на.текущем.месте  Зарплата.в.месяц  \
0                             0.5               400
1                меньше 3 месяцев               430
2                               1              2500
3                               4              2000
4                             0.5              4500
...                           ...               ...
8699             меньше 3 месяцев               700
8700                          0.5               400
8701                          0.5               800
8702                            4              2600
8703                            2              5000

      Изменение.зарплаты.за.12.месяцев    Город     Размер.компании  \
0                                    0  Харьков       до 10 человек
1                                  130  Харьков  свыше 1000 человек
2                                  800     Киев     до 1000 человек
3                                  400   Одесса      до 200 человек
4                                  500   Другой       до 10 человек
...                                ...      ...                 ...
8699                               700   Одесса       до 50 человек
8700                               120     Киев       до 50 человек
8701                               500    Львов       до 10 человек
8702                                 0    Днепр  свыше 1000 человек
8703                               800   Одесса     до 1000 человек

         Тип.компании      Пол  Возраст           Образование  Еще.студент  \
0      Аутсорсинговая  женский       20  Незаконченное высшее         True
1      Аутсорсинговая  женский       21  Незаконченное высшее         True
2      Аутсорсинговая  мужской       26                Высшее        False
3         Продуктовая  мужской       30               Среднее        False
4         Продуктовая  мужской       30    Техникум / Колледж        False
...               ...      ...      ...                   ...          ...
8699   Аутсорсинговая  мужской       23                Высшее        False
8700      Продуктовая  женский       22                Высшее        False
8701  Аутстаффинговая  мужской       30  Незаконченное высшее        False
8702   Аутсорсинговая  мужской       34                Высшее        False
8703      Продуктовая  мужской       28                Высшее        False

     Уровень.английского      Дата.заполнения  \
0          ниже среднего  12/06/2017 12:38:08
1          выше среднего  12/06/2017 12:42:51
2                средний  12/06/2017 13:02:47
3          ниже среднего  12/06/2017 13:03:01
4                средний  12/06/2017 13:03:47
...                  ...                  ...
8699             средний  12/07/2017 15:45:24
8700       ниже среднего  12/07/2017 17:00:06
8701       выше среднего  12/07/2017 17:32:26
8702         продвинутый  12/07/2017 18:14:59
8703       выше среднего  12/07/2017 21:28:57

                                             User.Agent   exp  \
0     Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   0.5
1     Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...   0.0
2     Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   4.0
3     Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...   5.0
4     Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...  10.0
...                                                 ...   ...
8699  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....   1.0
8700  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   0.5
8701  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   1.0
8702  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...   6.0
8703  Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X...   7.0

      current_job_exp  salary
0                 0.5     400
1                 0.0     430
2                 1.0    2500
3                 4.0    2000
4                 0.5    4500
...               ...     ...
8699              0.0     700
8700              0.5     400
8701              0.5     800
8702              4.0    2600
8703              2.0    5000

[8704 rows x 20 columns]

/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/4085463725.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]

In [26]:
# Знову порахуйте, яка частка пропусків міститься в кожній колонці і переконайтеся, що залишився тільки стовпець "Мова.програмування"
target_column = 'Язык.программирования'
df_cleaned = df[[target_column]]
for column in df.columns:
    if column != target_column and df[column].notnull().all():
        df_cleaned[column] = df[column]
miss_perc = df_cleaned.isnull().sum() / len(df) * 100
print(miss_perc)
print(df.columns)

Язык.программирования               44.232537
N                                    0.000000
Должность                            0.000000
Общий.опыт.работы                    0.000000
Опыт.работы.на.текущем.месте         0.000000
Зарплата.в.месяц                     0.000000
Изменение.зарплаты.за.12.месяцев     0.000000
Город                                0.000000
Размер.компании                      0.000000
Тип.компании                         0.000000
Пол                                  0.000000
Возраст                              0.000000
Образование                          0.000000
Еще.студент                          0.000000
Уровень.английского                  0.000000
Дата.заполнения                      0.000000
User.Agent                           0.000000
exp                                  0.000000
current_job_exp                      0.000000
salary                               0.000000
dtype: float64
Index(['N', 'Должность', 'Язык.программирования', 'Специализация',
       'Общий.опыт.работы', 'Опыт.работы.на.текущем.месте', 'Зарплата.в.месяц',
       'Изменение.зарплаты.за.12.месяцев', 'Город', 'Размер.компании',
       'Тип.компании', 'Пол', 'Возраст', 'Образование', 'Университет',
       'Еще.студент', 'Уровень.английского', 'Предметная.область',
       'Дата.заполнения', 'User.Agent', 'exp', 'current_job_exp', 'salary',
       'Валюта', 'cls'],
      dtype='object')

/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]
/var/folders/dj/31pxygkj1f15ml2gszf74_g00000gn/T/ipykernel_89960/338331675.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[column] = df[column]

In [32]:
# Видаліть усі рядки у вихідній таблиці за допомогою методу dropna
df_cleaned = df.dropna()
print(df_cleaned)

Empty DataFrame
Columns: [N, Должность, Язык.программирования, Специализация, Общий.опыт.работы, Опыт.работы.на.текущем.месте, Зарплата.в.месяц, Изменение.зарплаты.за.12.месяцев, Город, Размер.компании, Тип.компании, Пол, Возраст, Образование, Университет, Еще.студент, Уровень.английского, Предметная.область, Дата.заполнения, User.Agent, exp, current_job_exp, salary, Валюта, cls]
Index: []

In [31]:
# Визначте новий розмір таблиці за допомогою методу shape
df_cleaned = df.dropna()
print(df_cleaned.shape)

(0, 25)

In [33]:
# Створіть нову таблицю python_data, в якій будуть тільки рядки зі спеціалістами, які вказали мову програмування Python
python_data = df[df['Язык.программирования'] == 'Python']
print(python_data)

         N                 Должность Язык.программирования Специализация  \
12      13         Software Engineer                Python           NaN
68      69         Software Engineer                Python           NaN
87      88  Junior Software Engineer                Python           NaN
114    115  Junior Software Engineer                Python           NaN
143    144  Junior Software Engineer                Python           NaN
...    ...                       ...                   ...           ...
8546  8547         Software Engineer                Python           NaN
8625  8626         Software Engineer                Python           NaN
8635  8636  Senior Software Engineer                Python           NaN
8673  8674  Junior Software Engineer                Python           NaN
8695  8696         Software Engineer                Python           NaN

     Общий.опыт.работы Опыт.работы.на.текущем.месте  Зарплата.в.месяц  \
12                   1             меньше 3 месяцев               800
68                 1.5                          0.5               900
87                 0.5                          0.5               600
114                1.5                          0.5               685
143                  1                            1               750
...                ...                          ...               ...
8546                 5                            1              2000
8625                 4                            1              1750
8635    10 и более лет             меньше 3 месяцев              4000
8673               0.5                          0.5               350
8695                 1                          0.5              1500

      Изменение.зарплаты.за.12.месяцев      Город     Размер.компании  \
12                                 200       Киев       до 50 человек
68                                 900       Киев       до 10 человек
87                                   0       Киев       до 10 человек
114                                250       Киев     до 1000 человек
143                                250       Киев       до 10 человек
...                                ...        ...                 ...
8546                               800  Запорожье       до 50 человек
8625                                 0       Киев  свыше 1000 человек
8635                              1300   Удаленно       до 10 человек
8673                                50       Киев       до 50 человек
8695                              1000       Киев       до 10 человек

        Тип.компании      Пол  Возраст           Образование  \
12    Аутсорсинговая  мужской       26                Высшее
68           Стартап  мужской       21  Незаконченное высшее
87    Аутсорсинговая  мужской       19  Незаконченное высшее
114   Аутсорсинговая  мужской       21  Незаконченное высшее
143   Аутсорсинговая  мужской       21  Незаконченное высшее
...              ...      ...      ...                   ...
8546  Аутсорсинговая  мужской       22  Незаконченное высшее
8625  Аутсорсинговая  мужской       28               Среднее
8635         Стартап  мужской       33                Высшее
8673  Аутсорсинговая  мужской       22                Высшее
8695         Стартап  мужской       29                Высшее

           Университет  Еще.студент Уровень.английского  \
12          НТУУ «КПИ»        False       ниже среднего
68    КНУ им. Шевченко         True       выше среднего
87          НТУУ «КПИ»         True       выше среднего
114         НТУУ «КПИ»        False             средний
143         НТУУ «КПИ»         True       выше среднего
...                ...          ...                 ...
8546        Другой вуз        False             средний
8625               NaN        False             средний
8635            ДонНТУ        False       выше среднего
8673        НТУУ «КПИ»        False             средний
8695            ДонНТУ        False             средний

             Предметная.область      Дата.заполнения  \
12        Веб-разработка,Другое  12/06/2017 13:05:54
68               Веб-разработка  12/06/2017 13:11:17
87     Веб-разработка,eCommerce  12/06/2017 13:12:25
114                      Другое  12/06/2017 13:14:52
143              Веб-разработка  12/06/2017 13:19:10
...                         ...                  ...
8546             Веб-разработка  10/07/2017 14:11:26
8625             Веб-разработка  11/07/2017 16:15:40
8635             Веб-разработка  11/07/2017 17:51:36
8673             Веб-разработка  12/07/2017 09:37:16
8695  Финансы и банки,eCommerce  12/07/2017 14:39:21

                                             User.Agent   exp  \
12    Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...   1.0
68    Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   1.5
87    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   0.5
114   Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   1.5
143   Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   1.0
...                                                 ...   ...
8546  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...   5.0
8625  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....   4.0
8635  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...  10.0
8673  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....   0.5
8695  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   1.0

      current_job_exp  salary Валюта  cls
12                0.0     800    NaN  DEV
68                0.5     900    NaN  DEV
87                0.5     600    NaN  DEV
114               0.5     685    NaN  DEV
143               1.0     750    NaN  DEV
...               ...     ...    ...  ...
8546              1.0    2000    NaN  DEV
8625              1.0    1750    NaN  DEV
8635              0.0    4000    NaN  DEV
8673              0.5     350    NaN  DEV
8695              0.5    1500    NaN  DEV

[207 rows x 25 columns]

In [35]:
# Визначте розмір таблиці python_data за допомогою методу shape
python_data = df[df['Язык.программирования'] == 'Python']
data_shape = python_data.shape
print(data_shape)

(207, 25)

In [38]:
# Використовуючи метод groupby, виконайте групування за стовпчиком "Посада"
grouped_by_position = df.groupby('Должность')
grouped_count = grouped_by_position.size()
print(grouped_count)

Должность
Business analyst                               150
DBA                                             26
Data Scientist / Data Analyst                   79
Designer                                       223
DevOps                                         170
Director of Engineering / Program Director      44
ERP / CRM                                       12
Game designer                                   18
HR                                             247
HTML coder                                     156
Junior QA engineer                             404
Junior Software Engineer                      1280
Marketing                                      138
Product Manager                                 87
Project manager                                371
QA Tech Lead                                    79
QA engineer                                    738
Research Engineer                               14
Sales manager                                   85
Scrum Master                                    19
Security Specialist                             12
Senior Project Manager / Program Manager        66
Senior QA engineer                             263
Senior Software Engineer                      1080
Software Engineer                             2168
Support                                        115
Sysadmin                                       129
System Architect                                65
Talent Researcher                               36
Team lead                                      152
Technical Lead                                 250
Technical writer                                28
dtype: int64

In [39]:
# Створіть новий DataFrame, де для згрупованих даних за стовпчиком "Посада", виконайте агрегацію даних за допомогою методу agg і знайдіть мінімальне та максимальне значення у стовпчику "Зарплата.в.місяць"
aggregated_data = df.groupby('Должность').agg({'Зарплата.в.месяц': ['min', 'max']})
print(aggregated_data)

                                           Зарплата.в.месяц
                                                        min    max
Должность
Business analyst                                        200   5000
DBA                                                     380   6000
Data Scientist / Data Analyst                           150   8000
Designer                                                100   4000
DevOps                                                  194  10000
Director of Engineering / Program Director             1500  34000
ERP / CRM                                               100   6000
Game designer                                           150   6800
HR                                                      100   7000
HTML coder                                              154   3000
Junior QA engineer                                       96   2000
Junior Software Engineer                                 75   2600
Marketing                                               100   4000
Product Manager                                         250   5000
Project manager                                         190   8000
QA Tech Lead                                            430   6000
QA engineer                                             150   2900
Research Engineer                                       114   4000
Sales manager                                           120   2300
Scrum Master                                            370   4500
Security Specialist                                     300   4000
Senior Project Manager / Program Manager                200   9100
Senior QA engineer                                      400   6000
Senior Software Engineer                                350   9200
Software Engineer                                       100   7000
Support                                                 138   3650
Sysadmin                                                 90   3000
System Architect                                        400  10000
Talent Researcher                                       100   1700
Team lead                                               300   7000
Technical Lead                                          500  18000
Technical writer                                        200   3000

In [41]:
import pandas as pd

# Створіть функцію fill_avg_salary, яка повертатиме середнє значення заробітної плати на місяць.
#  Використовуйте її для методу apply та створіть новий стовпчик "avg"

# Функція для віявлення середьної зарплатні
def fill_avg_salary(row):
    return row['Зарплата.в.месяц']

# Створюємо новий стовпчик
df['avg'] = df.apply(fill_avg_salary, axis=1)

print(df['avg'].describe())
df.to_csv('output_data.csv', index=False)

count     8704.000000
mean      1666.704159
std       1338.280986
min         75.000000
25%        600.000000
50%       1300.000000
75%       2400.000000
max      34000.000000
Name: avg, dtype: float64